extends: 'eslint:recommended'

env:
  es6: true
  node: true

rules:
  comma-spacing:
    - warn
    - {
      before: false,
      after: true,
    }
  eqeqeq:
    - warn
    - smart
  indent:
    - warn
    - 2
  linebreak-style:
    - warn
    - unix
  no-console:
    - off
  no-sync:
    - error
  no-var:
    - warn
  semi:
    - warn
    - always
  space-before-blocks:
    - warn
    - always
  space-before-function-paren:
    - warn
    - always
  strict:
    - error
  quotes:
    - warn
    - single
